create database db_invoice
    with owner postgres;

create table public."Invoice"
(
    id_invoice integer generated by default as identity
        constraint "PK_Invoice"
            primary key,
    amount     numeric,
    state      integer
);

alter table public."Invoice"
    owner to postgres;